# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_citswidget.ui'
#
# Created: Thu Oct 08 11:31:13 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CitsWidget(object):
    def setupUi(self, CitsWidget):
        CitsWidget.setObjectName(_fromUtf8("CitsWidget"))
        CitsWidget.resize(941, 867)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 7, 2, 1, 1)
        self.m_avgSpec = QtGui.QPushButton(self.dockWidgetContents)
        self.m_avgSpec.setObjectName(_fromUtf8("m_avgSpec"))
        self.gridLayout_2.addWidget(self.m_avgSpec, 0, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.m_openButton = QtGui.QPushButton(self.dockWidgetContents)
        self.m_openButton.setObjectName(_fromUtf8("m_openButton"))
        self.horizontalLayout.addWidget(self.m_openButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.line = QtGui.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 5, 2, 1, 1)
        self.map_layout = QtGui.QVBoxLayout()
        self.map_layout.setContentsMargins(0, 0, -1, -1)
        self.map_layout.setObjectName(_fromUtf8("map_layout"))
        self.m_mapWidget = MatplotlibWidget(self.dockWidgetContents)
        self.m_mapWidget.setMinimumSize(QtCore.QSize(440, 440))
        self.m_mapWidget.setObjectName(_fromUtf8("m_mapWidget"))
        self.map_layout.addWidget(self.m_mapWidget)
        self.gridLayout_2.addLayout(self.map_layout, 10, 2, 1, 1)
        self.spec_layout = QtGui.QVBoxLayout()
        self.spec_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.spec_layout.setContentsMargins(0, -1, -1, -1)
        self.spec_layout.setObjectName(_fromUtf8("spec_layout"))
        self.m_specWidget = MatplotlibWidget(self.dockWidgetContents)
        self.m_specWidget.setObjectName(_fromUtf8("m_specWidget"))
        self.spec_layout.addWidget(self.m_specWidget)
        self.gridLayout_2.addLayout(self.spec_layout, 10, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.m_avgBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.m_avgBox.setObjectName(_fromUtf8("m_avgBox"))
        self.horizontalLayout_3.addWidget(self.m_avgBox)
        self.m_derivBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.m_derivBox.setObjectName(_fromUtf8("m_derivBox"))
        self.horizontalLayout_3.addWidget(self.m_derivBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.m_channelBox = QtGui.QComboBox(self.dockWidgetContents)
        self.m_channelBox.setObjectName(_fromUtf8("m_channelBox"))
        self.horizontalLayout_2.addWidget(self.m_channelBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.m_clearSpec = QtGui.QPushButton(self.dockWidgetContents)
        self.m_clearSpec.setObjectName(_fromUtf8("m_clearSpec"))
        self.gridLayout_2.addWidget(self.m_clearSpec, 1, 3, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.m_belowBox = QtGui.QSpinBox(self.dockWidgetContents)
        self.m_belowBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m_belowBox.setMaximum(100)
        self.m_belowBox.setProperty("value", 50)
        self.m_belowBox.setObjectName(_fromUtf8("m_belowBox"))
        self.gridLayout.addWidget(self.m_belowBox, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.m_aboveBox = QtGui.QSpinBox(self.dockWidgetContents)
        self.m_aboveBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m_aboveBox.setMaximum(100)
        self.m_aboveBox.setProperty("value", 50)
        self.m_aboveBox.setObjectName(_fromUtf8("m_aboveBox"))
        self.gridLayout.addWidget(self.m_aboveBox, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.m_aboveBar = QtGui.QProgressBar(self.dockWidgetContents)
        self.m_aboveBar.setProperty("value", 50)
        self.m_aboveBar.setTextVisible(False)
        self.m_aboveBar.setOrientation(QtCore.Qt.Vertical)
        self.m_aboveBar.setInvertedAppearance(True)
        self.m_aboveBar.setObjectName(_fromUtf8("m_aboveBar"))
        self.gridLayout.addWidget(self.m_aboveBar, 2, 2, 1, 1)
        self.m_belowBar = QtGui.QProgressBar(self.dockWidgetContents)
        self.m_belowBar.setProperty("value", 50)
        self.m_belowBar.setTextVisible(False)
        self.m_belowBar.setOrientation(QtCore.Qt.Vertical)
        self.m_belowBar.setObjectName(_fromUtf8("m_belowBar"))
        self.gridLayout.addWidget(self.m_belowBar, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.m_avgVButton = QtGui.QPushButton(self.dockWidgetContents)
        self.m_avgVButton.setObjectName(_fromUtf8("m_avgVButton"))
        self.gridLayout.addWidget(self.m_avgVButton, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.m_viewSelectedBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.m_viewSelectedBox.setObjectName(_fromUtf8("m_viewSelectedBox"))
        self.gridLayout.addWidget(self.m_viewSelectedBox, 4, 2, 1, 1)
        self.m_belowLine = QtGui.QLineEdit(self.dockWidgetContents)
        self.m_belowLine.setReadOnly(True)
        self.m_belowLine.setObjectName(_fromUtf8("m_belowLine"))
        self.gridLayout.addWidget(self.m_belowLine, 3, 0, 1, 1)
        self.m_aboveLine = QtGui.QLineEdit(self.dockWidgetContents)
        self.m_aboveLine.setReadOnly(True)
        self.m_aboveLine.setObjectName(_fromUtf8("m_aboveLine"))
        self.gridLayout.addWidget(self.m_aboveLine, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 8, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.m_voltageBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.m_voltageBox.setDecimals(0)
        self.m_voltageBox.setObjectName(_fromUtf8("m_voltageBox"))
        self.horizontalLayout_4.addWidget(self.m_voltageBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 2, 1, 1)
        self.m_scaleVoltage = QtGui.QCheckBox(self.dockWidgetContents)
        self.m_scaleVoltage.setChecked(True)
        self.m_scaleVoltage.setObjectName(_fromUtf8("m_scaleVoltage"))
        self.gridLayout_2.addWidget(self.m_scaleVoltage, 2, 3, 1, 1)
        self.m_colorBarBox = QtGui.QComboBox(self.dockWidgetContents)
        self.m_colorBarBox.setObjectName(_fromUtf8("m_colorBarBox"))
        self.gridLayout_2.addWidget(self.m_colorBarBox, 4, 2, 1, 1)
        self.m_scaleMetric = QtGui.QCheckBox(self.dockWidgetContents)
        self.m_scaleMetric.setObjectName(_fromUtf8("m_scaleMetric"))
        self.gridLayout_2.addWidget(self.m_scaleMetric, 3, 3, 1, 1)
        self.m_vLineBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.m_vLineBox.setObjectName(_fromUtf8("m_vLineBox"))
        self.gridLayout_2.addWidget(self.m_vLineBox, 4, 3, 1, 1)
        CitsWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(CitsWidget)
        QtCore.QMetaObject.connectSlotsByName(CitsWidget)

    def retranslateUi(self, CitsWidget):
        CitsWidget.setWindowTitle(_translate("CitsWidget", "STM Data Analysis", None))
        self.label_2.setText(_translate("CitsWidget", "Average with respect to values", None))
        self.m_avgSpec.setText(_translate("CitsWidget", "Average on map", None))
        self.m_openButton.setText(_translate("CitsWidget", "Open CITS", None))
        self.m_avgBox.setText(_translate("CitsWidget", "Average spectra by selection", None))
        self.m_derivBox.setText(_translate("CitsWidget", "Plot derivative", None))
        self.label_7.setText(_translate("CitsWidget", "Displayed channel", None))
        self.m_clearSpec.setText(_translate("CitsWidget", "Clear spectra", None))
        self.label_6.setText(_translate("CitsWidget", "% of colormap", None))
        self.label_3.setText(_translate("CitsWidget", "Minimum value for the below averaging", None))
        self.label_4.setText(_translate("CitsWidget", "Maximum value for the above averaging", None))
        self.m_avgVButton.setText(_translate("CitsWidget", "Start the averaging", None))
        self.label_5.setText(_translate("CitsWidget", "% of colormap", None))
        self.m_viewSelectedBox.setText(_translate("CitsWidget", "View selected spectra", None))
        self.label.setText(_translate("CitsWidget", "Voltage", None))
        self.m_scaleVoltage.setText(_translate("CitsWidget", "Scale in Volts", None))
        self.m_scaleMetric.setText(_translate("CitsWidget", "Scale in metric units", None))
        self.m_vLineBox.setText(_translate("CitsWidget", "Voltage guideline", None))

from matplotlibwidget import MatplotlibWidget
